joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

left_motor_1:
  type: "velocity_controllers/JointVelocityController"
  joint: Acople_1__rueda_1

left_motor_2:
  type: "velocity_controllers/JointVelocityController"
  joint: Acople_2__rueda_2

left_motor_3:
  type: "velocity_controllers/JointVelocityController"
  joint: Acople_3__rueda_3

right_motor_1:
  type: "velocity_controllers/JointVelocityController"
  joint: Acople_4__rueda_4

right_motor_2:
  type: "velocity_controllers/JointVelocityController"
  joint: Acople_5__rueda_5

right_motor_3:
  type: "velocity_controllers/JointVelocityController"  ##effort_controllers/JointEffortController
  joint: Acople_6__rueda_6
