#PARAMETROS DEL MODELO DEL ROBOT:
# RADIO DE RUEDA:
radius : 0.075

# Ubicaciones ruedas derechas
alpha_r1 : 1.04041
beta_r1 : 2.10117
l_r1 : 0.3197035

alpha_r2 : 0
beta_r2 : 3.14159
l_r2 : 0.254275

alpha_r3 : -1.04041
beta_r3 : -2.10117
l_r3 : 0.3197035

# Ubicaciones ruedas izquierdas
alpha_l1 : 2.10117
beta_l1 : 1.04041
l_l1 : 0.3197035

alpha_l2 : 3.14159
beta_l2 : 0
l_l2 : 0.254575

alpha_l3 : -2.10117
beta_l3 : -1.04041
l_l3 : 0.3197035

#PARAMETROS DEL ROBOT
w_max : 6.6                        #VELOCIDAD ANGULAR MAXIMA
vel_cruc : 1.7                     #VELOCIDAD DE CRUCERO TRASLACIONAL

#PARAMETROS DE COORDENADAS Y TRAYECTORIA
coordenadas : [[-3.5, 3.5],
              [ 1.5, 3.5],
              [ 1.5,-1.5],
              [ 3.5,-1.5],
              [ 3.5,-8.0],
              [-2.5,-8.0],
              [-2.5,-5.5],
              [ 1.5,-5.5],
              [ 1.5,-3.5],
              [-1.0,-3.5]]
ds : 1                             #DISTANCIAMIENTO ENTRE PUNTOS DE TRAYECTORIA
num_coor_tray : 0

#PARAMETROS DEL PROGRAMA
f : 50                             #FRECUENCIA DE PUBLICACION

#PARAMETROS DEL CONTROLADOR DEL ROBOT
Kp : [ 5, 0.05,-2]                 #COEFICIENTES DEL CONTROLADOR PROPORCIONAL